# autoSuggestions config
unsetopt correct # autocorrect commands

setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered

# auto complete options
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name "" # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

#      bindkey '^I' forward-word         # tab
#      bindkey '^[[Z' backward-word      # shift+tab
#      bindkey '^ ' autosuggest-accept   # ctrl+space

function git_smart_rebase() {
    GIT_STASH_MESSAGE="git_smart_rebase: $RANDOM"
    git stash push -m "$GIT_STASH_MESSAGE"
    git fetch && git rebase
    git stash list | (grep "${GIT_STASH_MESSAGE}" && git stash pop) || true
}
