# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a984b37e-f1e0-41f8-914a-39f1350f778d";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/a984b37e-f1e0-41f8-914a-39f1350f778d";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/E3F8-9731";
      fsType = "vfat";
    };

  fileSystems."/.swapvol" =
    {
      device = "/dev/disk/by-uuid/a984b37e-f1e0-41f8-914a-39f1350f778d";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/persist" =
    {
      device = "/dev/disk/by-uuid/a984b37e-f1e0-41f8-914a-39f1350f778d";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
